# Generated by Django 4.0.8 on 2023-02-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faqs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_uz', models.CharField(max_length=255, verbose_name='Вопрос uz')),
                ('faq_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос ru')),
                ('faq_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вопрос en')),
                ('answer_uz', models.CharField(max_length=255, verbose_name='Ответ uz')),
                ('answer_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ ru')),
                ('answer_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ответ en')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
