# Generated by Django 4.0.8 on 2023-02-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqs',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False, verbose_name='order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ответ en'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ответ ru'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='answer_uz',
            field=models.CharField(max_length=500, verbose_name='Ответ uz'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='faq_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Вопрос en'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='faq_ru',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Вопрос ru'),
        ),
        migrations.AlterField(
            model_name='faqs',
            name='faq_uz',
            field=models.CharField(max_length=500, verbose_name='Вопрос uz'),
        ),
    ]
